pipeline {
    agent any

    environment {
        AWS_CREDS = credentials('aws-eks-creds')
    }

    stages {
        stage('Checkout') {
            steps { git 'https://github.com/your-repo/terraform-eks.git' }
        }

        stage('Terraform Init') {
            steps {
                sh '''
                terraform init
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                terraform plan
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                terraform apply -auto-approve
                '''
            }
        }
    }
}

