pipeline {
    agent any

    stages {

        stage('Show Workspace Info') {
            steps {
                sh 'echo "======== WORKSPACE ========="'
                sh 'pwd'
                sh 'echo "======== ROOT FILES ======="'
                sh 'ls -l'
            }
        }

        stage('Checkout Repo') {
            steps {
                git url: 'https://github.com/Jithendarramagiri1998/snake-game.git', branch: 'main'
            }
        }

        stage('After Checkout - Verify Repo') {
            steps {
                sh 'echo "======== AFTER CHECKOUT ======="'
                sh 'pwd'
                sh 'ls -l'
                sh 'echo "======== CHECK TERRAFORM DIR ======="'
                sh 'ls -l terraform-eks || echo "terraform-eks NOT FOUND"'
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform-eks') {
                    sh 'echo "======== TERRAFORM DIR ======="'
                    sh 'pwd'
                    sh 'ls -l'
                    sh 'terraform version'
                    sh 'terraform plan'
                }
            }
        }
    }
}
