pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Select Terraform action'
        )
    }

    stages {

        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform-eks') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform-eks') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            when { expression { params.ACTION == 'apply' } }
            steps {
                dir('terraform-eks') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            when { expression { params.ACTION == 'apply' } }
            steps {
                dir('terraform-eks') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Terraform Destroy') {
            when { expression { params.ACTION == 'destroy' } }
            steps {
                dir('terraform-eks') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}
